package com.miguelcr.a01_databasegreendao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CLASE_DB".
 */
@Entity
public class ClaseDB {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String nombre;

    @Generated(hash = 1913655552)
    public ClaseDB() {
    }

    public ClaseDB(Long id) {
        this.id = id;
    }

    @Generated(hash = 1443640152)
    public ClaseDB(Long id, @NotNull String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(@NotNull String nombre) {
        this.nombre = nombre;
    }

    @Override
    public String toString() {
        return getNombre();
    }
}
