package com.miguelcr.a01_databasegreendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.miguelcr.a01_databasegreendao.model.AlumnoDB;
import com.miguelcr.a01_databasegreendao.model.ClaseDB;

import com.miguelcr.a01_databasegreendao.dao.AlumnoDBDao;
import com.miguelcr.a01_databasegreendao.dao.ClaseDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alumnoDBDaoConfig;
    private final DaoConfig claseDBDaoConfig;

    private final AlumnoDBDao alumnoDBDao;
    private final ClaseDBDao claseDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alumnoDBDaoConfig = daoConfigMap.get(AlumnoDBDao.class).clone();
        alumnoDBDaoConfig.initIdentityScope(type);

        claseDBDaoConfig = daoConfigMap.get(ClaseDBDao.class).clone();
        claseDBDaoConfig.initIdentityScope(type);

        alumnoDBDao = new AlumnoDBDao(alumnoDBDaoConfig, this);
        claseDBDao = new ClaseDBDao(claseDBDaoConfig, this);

        registerDao(AlumnoDB.class, alumnoDBDao);
        registerDao(ClaseDB.class, claseDBDao);
    }
    
    public void clear() {
        alumnoDBDaoConfig.getIdentityScope().clear();
        claseDBDaoConfig.getIdentityScope().clear();
    }

    public AlumnoDBDao getAlumnoDBDao() {
        return alumnoDBDao;
    }

    public ClaseDBDao getClaseDBDao() {
        return claseDBDao;
    }

}
